version: '2'
services:
  influxdb:
    image: monstrenyatko/rpi-influxdb
    container_name: influxdb
    volumes:
      - influxdb-config:/config:ro
      - influxdb-data:/data
    ports:
      - "8086:8086"
    restart: unless-stopped
volumes:
  influxdb-config:
    external: true
  influxdb-data:
    external: true