version: '2'
services:
  influxdb:
    image: monstrenyatko/rpi-influxdb
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb:rw
    ports:
      - "8086:8086"
    restart: unless-stopped
volumes:
  influxdb-data:
